# Generated by Django 3.2 on 2021-04-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210419_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question_text',
        ),
    ]
